name: shout-to-the-server
on:
  push:
    branches:
      - master
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://utfood.vercel.app/api/run' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
